spring:
  threads:
    virtual:
      enabled: true # The Project Loom Magic
  data:
    redis:
      host: localhost
      port: 6379
  Kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health, Prometheus
